name: Build and Release ESPeccy Firmware

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [default, nopsram]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install platformio setuptools

    - name: Build ESPeccy firmware
      run: platformio run -e ${{ matrix.env }}

    - name: Upload ESPeccy firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ESPeccy-firmware-${{ matrix.env }}
        path: |
          .pio/build/${{ matrix.env }}/firmware.bin
          .pio/build/${{ matrix.env }}/bootloader.bin
          .pio/build/${{ matrix.env }}/partitions.bin

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Build Artifacts (default)
      uses: actions/download-artifact@v4
      with:
        name: ESPeccy-firmware-default
        path: ./firmwares/default

    - name: Download Build Artifacts (nopsram)
      uses: actions/download-artifact@v4
      with:
        name: ESPeccy-firmware-nopsram
        path: ./firmwares/nopsram

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Update Release
      run: |
        gh release edit "${{ github.ref_name }}" --title "Release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install esptool
      run: python -m pip install esptool

    - name: Merge firmware binaries into one image (default)
      run: |
        esptool.py --chip esp32 merge_bin -o ./firmwares/complete_firmware.bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          0x1000 ./firmwares/default/bootloader.bin \
          0x8000 ./firmwares/default/partitions.bin \
          0x40000 ./firmwares/default/firmware.bin

    - name: Merge firmware binaries into one image (nopsram)
      run: |
        esptool.py --chip esp32 merge_bin -o ./firmwares/complete_firmware_nopsram.bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          0x1000 ./firmwares/nopsram/bootloader.bin \
          0x8000 ./firmwares/nopsram/partitions.bin \
          0x40000 ./firmwares/nopsram/firmware.bin

    - name: Get Release Upload URL
      id: get_release
      run: |
        url=$(gh release view "${{ github.ref_name }}" --json uploadUrl -q .uploadUrl)
        echo "upload_url=$url" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Complete Firmware (default) to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.upload_url }}
        asset_path: ./firmwares/complete_firmware.bin
        asset_name: complete_firmware.bin
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Complete Firmware (nopsram) to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.upload_url }}
        asset_path: ./firmwares/complete_firmware_nopsram.bin
        asset_name: complete_firmware_nopsram.bin
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Firmware Upgrade (default) to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.upload_url }}
        asset_path: ./firmwares/default/firmware.bin
        asset_name: firmware.upg
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Firmware Upgrade (nopsram) to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.upload_url }}
        asset_path: ./firmwares/nopsram/firmware.bin
        asset_name: firmware_nopsram.upg
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
